### PR TITLE
Headers.append + Headers.set fixes

### LINKED ISSUE #60: headers values can be an array
When using the module to fetch an OAUTH token from twitter's api, they return a `set-cookie` header that undici parses as an array. 

The typings support it as well:
https://github.com/nodejs/undici/blob/8d968591620f6b89348ad823f7b82d1ecd5e528a/types/dispatcher.d.ts#L47
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2563cecd0398fd9337b2806059446fb9d29abec2/types/node/http.d.ts#L7

I have no idea how to replicate the issue without using twitter's API that requires authorization to use. Not only this I don't really know how you would want to handle this since I know you put a lot of time into increasing header performance.

edit: forgot to mention that when the values are an array it throws an error when normalizing them

### PR DESCRIPTION
**Pull request by KhafraDev**
Closes #60 

Should cover everything but there's a good chance I missed something!

### CODE REVIEW

**Comment by ronag** [comment]
I dont' think this matches the spec https://developer.mozilla.org/en-US/docs/Web/API/Headers/set

**Comment by KhafraDev** [comment]
> I dont' think this matches the spec https://developer.mozilla.org/en-US/docs/Web/API/Headers/set

image

works in Firefox, maybe it's not documented on mdn?

**Comment by ronag** [comment]
Interesting objects also work but get stringified:

```
const h = new Headers()
undefined
h.set('asd', {})
undefined
h.get('asd')
"[object Object]"
```

The spec is not clear at all on what do to in regards to the type of `value`.

**Comment by KhafraDev** [comment]
yeah, it seems like everything is just stringified. I'll work on mimicking the behavior.

**Comment by Ethan-Arrowood** [comment]
As I understand the spec, values are first normalized:

> To normalize a potentialValue, remove any leading and trailing HTTP whitespace bytes from potentialValue.

Then, a TypeError should be thrown if value is not a value 

> A value is a byte sequence that matches the following conditions:
> Has no leading or trailing HTTP tab or space bytes.
> Contains no 0x00 (NUL) or HTTP newline bytes.

**Comment by Ethan-Arrowood** [comment]
I think the safest solution should be to just stringify whatever is passed to the `value` and document that behavior.

**Comment by Ethan-Arrowood** [comment]
I've opened an issue on the spec too https://github.com/whatwg/fetch/issues/1260

**Comment by KhafraDev** [comment]
Sounds good, as mentioned before I've opted for the same behavior Chrome/Firefox have when using non-string values. I've also left a notice under the append/set sections in the README for this behavior.

**Comment by Ethan-Arrowood** [comment]
The folks responded on the other issue. Looks like value is defined as a DOMString and should be handled as such. I wonder if we have anything for that in Node

**Comment by mcollina** [comment]
I would call `.toString()` to all inputs and return a string.
https://developer.mozilla.org/en-US/docs/Web/API/DOMString

**Comment by Ethan-Arrowood** [comment]
Oh that's easy enough!

**Comment by KhafraDev** [comment]
Currently the PR:

1. Enforces 2 arguments in Headers.append and Headers.set
2. stringifys all values passed with template literals (symbols still throw an error)

is there anything I should change?

**Comment by ronag** [comment]
What about arrays? They are not stringified Chrome?

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by Ethan-Arrowood** [comment]
This looks good to me! Great work on the tests too

**Pull request merged**
