### PR TITLE
Convert undici RequestAbortedError to AbortError

### PR DESCRIPTION
**Pull request by timdp**
The [Fetch spec](https://fetch.spec.whatwg.org/) mandates that an abort signal be turned into an `AbortError`.

### CODE REVIEW

**Comment by timdp** [comment]
The test timeouts are something I observed locally as well. I fixed them as part of #29. I suspect a dependency introduced a regression - probably good to check in package-lock.json to avoid that.

**Review by Ethan-Arrowood — APPROVED** [review]
good change. yeah lets fix up the CI and then this is good to merge

**Comment by Ethan-Arrowood** [comment]
Sorry it took a bit of time; im in the middle of a move. I've merged the other PR so update this one when you get a chance and when the CI passes we can get it merged

**Comment by timdp** [comment]
Will do. Moving is the worst. Hang in there!

**Comment by timdp** [comment]
Updated!

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by Ethan-Arrowood** [comment]
Woo! Great work! Thank you again 😄

**Comment by timdp** [comment]
Happy to contribute!

**Pull request merged**
